# Generated by Django 3.1.2 on 2020-10-13 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0002_auto_20201013_1135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cache',
        ),
    ]
